query($searchParam: String, $page: Int) {
  mangaByName(searchParam: $searchParam, page: $page) {
    data {
      name
      id
      synopsis
      genre
    }
    paginatorInfo {
      currentPage
      lastPage
    }
  }
}
